FIND_PATH(FFTW3_INCLUDE_DIR NAMES fftw3.h)
MARK_AS_ADVANCED(FFTW3_INCLUDE_DIR)
 
FIND_LIBRARY(FFTW3_LIBRARY NAMES
fftw3
libfftw3
fftw3lib
)
MARK_AS_ADVANCED(FFTW3_LIBRARY)
 
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FFTW3 DEFAULT_MSG FFTW3_LIBRARY FFTW3_INCLUDE_DIR)
