FIND_PATH(PROGRAM_MAP_INCLUDE_DIR NAMES program-map.h)
MARK_AS_ADVANCED(PROGRAM_MAP_INCLUDE_DIR)
 
FIND_LIBRARY(PROGRAM_MAP_LIBRARY NAMES
program-map
libprogram-map
program-maplib
)
MARK_AS_ADVANCED(PROGRAM_MAP_LIBRARY)
 
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ProgramMap DEFAULT_MSG PROGRAM_MAP_LIBRARY PROGRAM_MAP_INCLUDE_DIR)
